server {
    listen 8080;
    server_name _;
    root /app/code;
    index index.html;

    location ~* \.mjs$ {
        types { text/javascript mjs; }
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}

